language: python
python:
    - "3.3"

install: "pip3 install -r requirements.txt"

env:
    - TESTS=tests.test_determinacy
    - TESTS=tests.test_actuality

script: "python3 -OOm unittest $TESTS -v"

