language: python
python:
    - "3.4"

install: "pip3 install -r requirements.txt"

env:
    - TRUNKS=Synonyms TESTS='-e test_determinacy'
    - TRUNKS=Synonyms TESTS=tests/test_determinacy.py

    - TRUNKS=Definitions TESTS='-e test_determinacy'
    - TRUNKS=Definitions TESTS=tests/test_determinacy.py

    - TRUNKS=Ngram TESTS='-e test_determinacy'
    - TRUNKS=Ngram TESTS=tests/test_determinacy.py

    - TRUNKS='%Synonyms %Definitions %Ngram' # all other, usually relatively fast

script: "python3 run_nose.py $TRUNKS -v $TESTS"

